### ISSUE TITLE
Comentarios de mejora

### ISSUE THREAD

**Issue by YifanYes** [elianajr/bubble-sorting-cards#1]
El gradiente del fondo y el efecto de las cartas está muy chulo ! Te cuento un par de cosillas para mejorar:

- Intenta usar el querySelector solo con ids, tienes uno con una clase. Es decir, reservamos las clases para CSS y los id para Javascript.
- Intenta imprimir en la pantalla los pasos de la ordenación, no el resultado de golpe. Eso lo consigues llamando a la función de pintar cartas dentro del bucle del algoritmo.
- La lógica del sort lo tienes dentro de un addEventListener. Te recomendaría que estuviese dentro de una función, y que esa función se llame en el evento onClick, así queda más legible.

**Comment by elianajr** [comment]
- Si cambio los querySelector a getElementsByClassName, me da error... según la documentación podría usar con el querySelector, pero si lo ves conveniente investigo más sobre el error
- Ya lo hice en 2 pasos la ordenación y optimicé que cuando sea 1, 10, 11, 12 devuelva A, J, Q, K
- Te refieres a algo así?
document.getElementById("demo").onclick = function() {myFunction()};

function myFunction() {
  document.getElementById("demo").innerHTML = "YOU CLICKED ME!";
}
